### PR TITLE
EASYOPAC-624 - Fix problem with slick js error.

### PR DESCRIPTION
**Pull request by bozeak**

### CODE REVIEW

**Comment by guddo** [comment]
No core changes :/

**Comment by bozeak** [comment]
@guddo But this is core issue! How shall we proceed now???

**Comment by bozeak** [comment]
@guddo This PR will not be needed if https://github.com/ding2/ding2/pull/912 PR will be integrated.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a8de85e44da4f55963bbc15d1d362ae6fa4ffdcf
  * Commits must be in the following format: [issue ID] - [short summary of change]

Guidelines are available at https://github.com/easySuite/ding2

---
This message was auto-generated by https://gitcop.com

**Comment by guddo** [comment]
@bozeak Fixed

**Pull request merged**
