### PR TITLE
DDBCMS-91 - Ding item viewer integration to DDB CMS

### PR DESCRIPTION
**Pull request by AnnaCaraman**

### CODE REVIEW

**Comment by guddo** [comment]
Guys @bozeak @makcumm - this should not be merged to master! I have rebased master. Please merge this to easyopac branch. /cc @AnnaCaraman

**Comment by makcumm** [comment]
@guddo So, what should i do? Revert PR and create new one, or just create new PR to easyopac branch?

**Comment by guddo** [comment]
@makcumm Create a new PR to easyopac branch - and branch out from easyopac ofc.

**Comment by guddo** [comment]
This is a DDBCMS case. It should be a PR against ding2/ding2:master, made by me.

**Pull request merged**
