### PR TITLE
EASYOPAC-819 - Store covers under item faust number name, operator lo…

### PR DESCRIPTION
**Pull request by AnatolyMuntean**
…gic fix.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 938f03d3f01c8d42dcb1dc4009cc53d9d7b54dc7
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/easySuite/ding2

---
This message was auto-generated by https://gitcop.com

**Comment by AnatolyMuntean** [comment]
Yes, as long as the specified module relies on ting covers and does not pull covers on it's own. Regarding backside covers - AFAIK those are PDF files. Should they get the same naming convention?

**Comment by guddo** [comment]
@AnatolyMuntean Yes.

**Comment by AnatolyMuntean** [comment]
https://github.com/easySuite/ting_covers_backside/pull/31/files

**Pull request merged**
