### PR TITLE
NO-TASK - Build easyopac and not ding2 make.

### PR DESCRIPTION
**Pull request by guddo**

### CODE REVIEW

**Comment by NicolaeGrigoriu** [comment]
Can't we use drupal 7.54.
https://ftp.drupal.org/files/projects/drupal-7.54.tar.gz
and not 7.45?

**Comment by NicolaeGrigoriu** [comment]
Based on the documentation we should use php 5.4 but there are many features from the php 5.5 and php 5.6. For example, expressions in the `empty()` function. Can we switch to the 5.6 version?

**Comment by guddo** [comment]
@NicolaeGrigoriu: Done - I don't know why this error appears with `ding_frontend.install`..

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cb1b33a78800c127781ff610fc7fa0b3d97e3d52
  * Commits must be in the following format: [issue ID] - [short summary of change]

 * Commit: 938f03d3f01c8d42dcb1dc4009cc53d9d7b54dc7
  * Your subject line is longer than 72 characters

 * Commit: 5c9ac48a3af2e267f055c8d5ea46ee274f56d7b8
  * Commits must be in the following format: [issue ID] - [short summary of change]

 * Commit: 3d9270ac0b5a4d3a8d0e1b2a21db26d982d08f4d
  * Commits must be in the following format: [issue ID] - [short summary of change]

 * Commit: 6a6b716ebd81adb767d788d56c6cea420361a03e
  * Commits must be in the following format: [issue ID] - [short summary of change]

 * Commit: c20d49bebad1a852654121091236c28e6f2eec07
  * Commits must be in the following format: [issue ID] - [short summary of change]

 * Commit: e636ec530d22904d7d3bfee5570b5b0c36e51be4
  * Commits must be in the following format: [issue ID] - [short summary of change]

 * Commit: d85151443d64160fc80d4b5cf6f7036a4d90480c
  * Commits must be in the following format: [issue ID] - [short summary of change]

Guidelines are available at https://github.com/easySuite/ding2

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
