### PR TITLE
EASYSUITE-2 - Toggle view styles fixes and scripts

### PR DESCRIPTION
**Pull request by AnnaCaraman**

### CODE REVIEW

**Comment by guddo** [comment]
241 changed files? This is not right.

**Comment by guddo** [comment]
@makcumm Who reviewed your commit? You should not CR/merge your own commits.

**Comment by makcumm** [comment]
@guddo NG made review, but hi dont have permissions to merge PR, so i made it.

**Comment by guddo** [comment]
@NicolaeGrigoriu Indent problems and file permissions changes should not be CR'ed OK :)

**Pull request merged**
