### PR TITLE
DDBEASY-783 - Export ting action buttons field for search_results display.

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**

### CODE REVIEW

**Comment by guddo** [comment]
This is wrong. It should be made as a standalone module, that's why we created ding_collection_reservation.

**Comment by NicolaeGrigoriu** [comment]
The problem was not with collections, but with the reservation button overall. This button is not visible neither on ting items.

**Comment by guddo** [comment]
But it does mean that ding_collection_reservation will not work without this change, right?

**Comment by NicolaeGrigoriu** [comment]
It means that reservation will not work at all.

**Comment by guddo** [comment]
So basically ding_collection_reservation is useless without these changes? Then there is no reason to make it as a standalone module.

**Pull request closed without merging**
