### PR TITLE
EASYOPAC-890 - Remove agency constraint.

### PR DESCRIPTION
**Pull request by AnatolyMuntean**

### CODE REVIEW

**Comment by guddo** [comment]
@AnatolyMuntean Why did you remove this constraint?

**Comment by AnatolyMuntean** [comment]
Because it's impossible to edit this field one the value is set.

**Comment by guddo** [comment]
Thats the purpose, but OK keep it changeable. Why did you remove the variable_del?

**Comment by AnatolyMuntean** [comment]
I added it, not removed.

**Pull request merged**
