### PR TITLE
EASYOPAC-222 - Update ting_reference for easyopac products.

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**

### CODE REVIEW

**Comment by guddo** [comment]
@NicolaeGrigoriu why do you change existing variable in `ding_page`?

**Comment by NicolaeGrigoriu** [comment]
> @NicolaeGrigoriu why do you change existing variable in ding_page?

I have changed variable because when we reverted ting_reference changed we skipped these.

**Comment by guddo** [comment]
No, we changed everything back to `_material` instead of `_materials`: https://github.com/easySuite/ding2/commit/63339c5bf7cee9903b48bb9e825894e48c00f1d9#diff-e7cf06165d355c0126239b92c516b83b

**Comment by NicolaeGrigoriu** [comment]
We changed everything except the ding_page.features.field_instance.inc file. It is changed in the .info file. The node-ding_page-field_ding_page_materials is changed however no changes are made in the instance.inc one.

**Comment by guddo** [comment]
Ok, so its a leftover - I understand, thanks.

**Pull request merged**
