### PR TITLE
EASYOPAC-1168 - Update the zAccordion library, unset the migrate for production.

### PR DESCRIPTION
**Pull request by NicolaeGrigoriu**
#### Link to issue

https://inlead.atlassian.net/browse/EASYOPAC-1168

#### Description

Remove the depricated function size() and use the length one for the zAccordion js library. Disabled the jquery_migrate option so the animation works properly.

#### Screenshot of the result
image

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 126aeffc8d8fa336fa7872122adb8177428c5527
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/easySuite/ding2

---
This message was auto-generated by https://gitcop.com

**Comment by guddo** [comment]
@NicolaeGrigoriu Why do you disable jquery_migrate?

**Comment by NicolaeGrigoriu** [comment]
@guddo because it stops the propagation of the animate effect. And, as far as I know all the jqueqy code we have is already ported to 3.1.1.

**Comment by guddo** [comment]
This will mean change in core and therefore diff, and I don't think its good: https://github.com/ding2/ding2/blob/master/modules/ding_base/ding_base.strongarm.inc#L679.

**Comment by NicolaeGrigoriu** [comment]
jQuery 3 the extra parameters that the easing functions expected are now deprecated. So, the library was removed since no easing library functions are not used in the zAccordion library.

**Pull request merged**
